### ISSUE TITLE
Docker 101

### ISSUE THREAD

**Issue by zcorleissen** [rackerlabs/docs-container-service#14]
@cyrichardson: https://docs.docker.com/reference/builder/ from Everett's workshop at DevEx Onsite

@DonNateR: Some subjects that doc might cover (kudos to Keith):

#. Install Docker and a Daemon (probably our own container service)
#. Pull an image from Docker hub (probably cirros or ubuntu)
#. Create/run the container and “prove” you’re in a container, not the host system

This might also be a good place for this topic (unless we want to make it a separate one):
#. Building images with Dockerfile

**Comment by DonNateR** [comment]
Since all Docker 101 related content is complete, I am going to go ahead and close this issue!

**Comment by rgbkrk** [comment]
:tada:
