### ISSUE TITLE
dvm integration with credentials zip

### ISSUE THREAD

**Issue by smashwilson** [rackerlabs/docs-container-service#173]
To improve user experience when working with different Docker daemons and Swarm clusters, @rgbkrk and I rolled up [dvm](https://github.com/rgbkrk/dvm). I have a PR in flight against the RCS backend to add a `DOCKER_VERSION` environment variable to give us some "integration":

```bash
source docker.env

dvm install
# or
dvm use
```

This is a start, but there are a few directions that could go from here, and I'm curious what others think about this from a developer experience standpoint.

#### 1. Auto-install dvm as part of docker.env or not

I _could_ add a check and automatic dvm install as part of the `docker.env`. That would reduce our entire on-ramping experience to "download this thing and source this file", but:

 * Installing additional software without explicit user consent feels rude to me. To mitigate, we could: add a prompt, with an environment variable override for unattended use-case; echo instructions for a user to do it themselves instead;
 * `dvm` is taken from `nvm`, which is pretty good about adapting to different shells and so on, but there's still the risk that it won't work for _someone's_ setup. Rolling it into the `docker.env` file means a rockier introduction for those users.

#### 2. The Windows experience

Because dvm is written in shell script, it doesn't address the Windows experience at all yet. There are a few directions we could go here:

* Implement (some subset of) dvm for Windows. This wouldn't be as bad as it sounds, at least not in Powershell. I think.
* Refactor (slash rewrite) dvm to use a Go binary for cross-platform installs; see rgbkrk/dvm#12. We would likely still want wrapper scripts, because the Go portion couldn't actually manipulate the shell's `${PATH}` directly (hence `docker-machine env`'s eval hack).
* Would we still be able to auto-install on Windows, too?

#### 3. Move dvm... somewhere

The dvm repo is currently just under @rgbkrk's personal GitHub account. For more legitimacy we'd probably want it to be hosted somewhere else.

* [/dvm](https://github.com/dvm) is taken on GitHub, but maybe we could grab `/docker-dvm` or something.
* `/rackerlabs` is a :-1: from @rgbkrk and myself because rackerlabs is a giant dumping ground.
* Maybe we could convince the Docker people to adopt it and move it under `/docker`?

Related to #116, #20, and probably others.

/cc @rgbkrk, @mdarby, @everett-toews, @carolynvs

**Comment by everett-toews** [comment]
We should hash out the verbiage for the copy-pastable tomorrow.

**Comment by everett-toews** [comment]
First draft of docker.env version verbiage.

```bash
echo "Carina is running Docker version $DOCKER_VERSION"
echo "If you already have the Docker client installed, you may get an error that \"client and server don't have same version\"."
echo "To work with multiple Docker versions, use dvm."
echo "Run these commands to configure your shell:"
echo "git clone https://github.com/rgbkrk/dvm.git ~/.dvm"
echo "source ~/.dvm/dvm.sh"
echo "dvm install $DOCKER_VERSION"
echo "dvm use $DOCKER_VERSION"
```

Ugh. 8 lines. It's awfully verbose. Can we get it down to 4?

@rgbkrk Does the carina cli have the dvm installer? How do they install the carina cli?

**Comment by rgbkrk** [comment]
Changed the originating repo to be getcarina, we'll move that today.

**Comment by rgbkrk** [comment]
As we said on video, the carina cli does *not* have a dvm installer. We could add it pretty simply, which would also mean we don't have to depend on the user having `git`.

**Comment by rgbkrk** [comment]
The title of this article is a finished issue, in that dvm recognizes the $DOCKER_VERSION variable.

The third statement is finished since getcarina now owns dvm. As for the first, we've decided against installing dvm using the credentials zip.

As for the second, Carolyn is on the case.

Can we close this one and rely on the Windows issues opened within the dvm repo?

**Comment by everett-toews** [comment]
:+1:

**Comment by everett-toews** [comment]
I'll leave it to @smashwilson to close...

**Comment by rgbkrk** [comment]
A single upboat is all I need, closing now.
