### ISSUE TITLE
Incorrect screenshots?

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-container-service#206]
The screenshot in **/_references/troubleshooting-port-unavailable.md** doesn't look like the correct interface. It looks like the Cloud Control Panel. The screenshot file is at **/_assets/img/troubleshooting-port-unavailable/grow-cluster.png**. Update it if necessary.

Also, the screenshots in **/_references/rcs-credentials.md** don't look like the correct interface. It looks like the Cloud Control Panel. The screenshots are at **/_assets/img/rcs-credentials**. Update it if necessary.

**Comment by carolynvs** [comment]
These are screenshots of the new (unreleased) UI, not the current UI. I just confirmed with Jesse and Keith that the UI will be live by the time we go live. So we are all set!

**Comment by kmsholcomb** [comment]
Ah, OK. I just saw the staging version of the new UI yesterday. I had no idea that it existed! Sorry for the false alarm.
