### ISSUE TITLE
Put Getting Started on Carina at the top of the Getting Started articles

### ISSUE THREAD

**Issue by everett-toews** [rackerlabs/docs-container-service#210]
Please put [Getting Started on Carina](https://github.com/rackerlabs/docs-container-service/blob/master/_tutorials/getting-started-on-carina.md) at the top of the Getting Started articles [here](https://github.com/rackerlabs/docs-container-service/blob/master/docs/index.html#L18).

**Comment by ktbartholomew** [comment]
Fixed w/ #289.
