### ISSUE TITLE
Change number of segments noted in Intro to Swarm?

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-container-service#211]
Just saw that they are "lowering quotas of MAX_NODES_PER_CLUSTER from 10 to 3." The [Introduction to Docker Swarm article](_tutorials/005-docker-swarm-intro.md) says, "Rackspace Container Service offers one segment by default and is scalable up to 10 segments." If that is the number affected by the change, then the article should be updated. Thanks!

**Comment by mdarby** [comment]
Updated in 04ab0c15d29403793937625fea5f6b6774d2966a -- Thanks!
