### ISSUE TITLE
https://boatboat.deconst.horse/ Features intro

### ISSUE THREAD

**Issue by catlook** [rackerlabs/docs-container-service#242]
The section under features contains 2 sentences that seem a bit disjointed.  I'd keep them consistent, either both addressing users or both addressing "You".  For example:

With Carina by Rackspace, users get a “zero infrastructure” hosted container environment with no need to worry about building, managing, and updating their container environments ever again.
or
With Carina by Rackspace, you get a “zero infrastructure” hosted container environment, and you don't have to worry about building, managing, and updating your container environments any more.

**Comment by lauracly** [comment]
Hi Cat,
I addressed this inconsistency with my update to the main page. We went with the "you" version.
