### ISSUE TITLE
https://boatboat.deconst.horse/ Best practises

### ISSUE THREAD

**Issue by catlook** [rackerlabs/docs-container-service#244]
I'd change the text in this section to:

Discover the current best practices in the container world. For example, what are data volumes, security, the Ambassador pattern? Also, learn about the best practices, not just for Carina, but for containers, in general.

**Comment by lauracly** [comment]
Hi Cat,

Updated this text to remove the question (thought that was a bit out of place with the other content). Refocused it around the content in the best practices: 

Review recommendations and industry standard approaches for Carina and containers, along with an introduction to advanced topics.
