### ISSUE TITLE
Update https://github.com/rackerlabs/docs-container-service/blob/master/index.html

### ISSUE THREAD

**Issue by lauracly** [rackerlabs/docs-container-service#250]
For https://github.com/rackerlabs/docs-container-service/blob/master/index.html
Remove everything but the first sentence under "Everything You Need to Know".  Keep only the Carina sentence.

**Comment by lauracly** [comment]
Also, Change Everything You Need to Know" to "Everything You Need to Get Started". Now that the doc content is only on the docs page, this doesn't make sense.

**Comment by jnoller** [comment]
on this
