### ISSUE TITLE
A Carina overview diagram 

### ISSUE THREAD

**Issue by everett-toews** [rackerlabs/docs-container-service#251]
We need a nice diagram of this for the Overview of Carina.

![carina](https://mycluster.rackspacecloud.com/images/make-swarm-diag-full.png)

**Comment by everett-toews** [comment]
- [ ] Outer blue box should be labelled "cluster"
- [ ] "lxc container" should be labelled "segment"

**Comment by DonNateR** [comment]
@everett-toews I actually was almost done with this diagram. I'll update the issue once the draft is done!

**Comment by DonNateR** [comment]
![carina-cluster 1 6](https://cloud.githubusercontent.com/assets/12628964/10640437/4698272a-77da-11e5-9e5d-03ee1a95287f.png)

Won't upload as a PNG, but here's a preview in case you wanted to make any tweaks!

**Comment by everett-toews** [comment]
- [ ] Openstack Control Panel should be OpenStack control plane
- [ ] Manage certifications should be Download certificates
- [ ] Move Docker CLI down to the same level as Cluster management UI
- [ ] Move Swarm manager out into the segment, there should only be one in the segment
- [ ] Can User not touch the top of the container?
- [ ] Review that we can use the Docker logo like that from [here](https://www.docker.com/brand-guidelines) and [here](https://www.docker.com/trademark-guidelines)
- [ ] Get a :+1: from @jnoller

**Comment by DonNateR** [comment]
@everett-toews can you clarify what you mean by "Move swarm manager out into the segment." There is only one swarm manager per segment. Are you referring to the swarm agent? 

And the user touches the top of the container through Docker CLI. I can change the lines from dotted to dashed to reflect this.

**Comment by everett-toews** [comment]
I am referring to the swarm manager container. Both of the containers labelled "Swarm manager" should be deleted from their current position. Create a single "Swarm manager" container outside the Segments but inside the Cluster box. 

Don't change any lines.

For the containers labelled "User docker container", the **word** "User" touches the rounded top of the container image. It makes it hard to read. Preferably the word "User" would not touch the rounded top of the container image.

**Comment by DonNateR** [comment]
![carina-cluster 1 6 1](https://cloud.githubusercontent.com/assets/12628964/10647203/aed14c96-77fc-11e5-9143-d72f40f7fd7a.png)

@everett-toews Here's my edits. @rgbkrk Jesse asked me to have you take a look at the diagram as well. If ya'll think it's ready I'll make a PR for it pronto.

**Comment by everett-toews** [comment]
- [ ] Openstack Control Panel should be Carina control plane
- [ ] Cluster management UI should be Carina management UI
- [ ] Download certifications should be Download certificates
- [ ] Have the line from Swarm manager actually originate from the top/bottom of the Swarm manager container image

Looking good!

**Comment by rgbkrk** [comment]
That looks great! Agree with Everett's last check boxes.

**Comment by rgbkrk** [comment]
On a side note, are there server images that look like racks instead of the desktop machine I keep in the garage for nostalgia?

**Comment by DonNateR** [comment]
There are. They look kind of like this:
![dedicated-server-medium](https://cloud.githubusercontent.com/assets/12628964/10648119/4ca49068-7802-11e5-930b-6418d1b4b2c7.png)

**Comment by DonNateR** [comment]
https://github.com/rackerlabs/docs-container-service/pull/265

**Comment by jamiehannaford** [comment]
@DonNateR @everett-toews Isn't there 1 Swarm Manager container _per segment_? 


```bash
jamie in ~/projects/amphora/test
› docker info | grep Nodes
Nodes: 2

jamie in ~/projects/amphora/test
› docker ps -a | grep manager
cb4d8c713d81        swarm                    "/swarm manage -H=tcp"   5 minutes ago       Up 5 minutes                    2375/tcp, 104.130.0.28:2376->2376/tcp   ff7d1498-96d4-496d-a144-7ea92b27239d-n2/swarm-manager
5a5ebfceef8b        swarm                    "/swarm manage -H=tcp"   3 days ago          Up 2 hours                      2375/tcp, 104.130.0.23:2376->2376/tcp   ff7d1498-96d4-496d-a144-7ea92b27239d-n1/swarm-manager
```

In the diagram you have 1 per cluster.

**Comment by everett-toews** [comment]
That's changing before launch.
