### ISSUE TITLE
Nuke containers tutorial doesn't have a Next Steps section

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-container-service#294]
This looks like a reference type procedure, and I don't think it needs a Next Steps, but the checklist mentioned that all tutorials should have them.  

https://github.com/rackerlabs/docs-container-service/blob/master/_tutorials/032-nuke-a-container.md

**Comment by kmsholcomb** [comment]
Ah, right, it is more of a troubleshooting topic. No next steps necessary. I'll revise the checklist. Thanks, Margaret!
