### ISSUE TITLE
Run Magento in Docker Tutorial - link issue

### ISSUE THREAD

**Issue by catlook** [rackerlabs/docs-container-service#307]
Article: https://getcarina.com/docs/tutorials/magento-in-docker/#modify-the-configuration hasa broken internal link.

Down in section "Verify and set up hosts", it tries to link back to section"Modify the configuration".  This link does not work.

@jamiehannaford

**Comment by kmsholcomb** [comment]
I fixed the link, but the article gives instructions for using Cloud Databases (which we are trying to avoid at the moment). So, we are going to move the article to the _M2 folder for now, until it can be updated.
