### ISSUE TITLE
Run wordpress across link front-end - no next step

### ISSUE THREAD

**Issue by catlook** [rackerlabs/docs-container-service#316]
According to our article QE checklist, all tutorials should have a next steps section:

Verify that each tutorial has a “Next step” section. If it does not, open an issue against the article. 
Note: Articles in the Tutorials section that are reference or troubleshooting articles and would not logically have a next step are exempt from this requirement. 

This article doesn't have a next steps section.  @jamiehannaford

**Comment by jamiehannaford** [comment]
I took it out because the next step linked to a tutorial which used external Rackspace services. Does it make sense to have a Next step until this final tutorial gets re-enabled?

cc/ @lauracly @everett-toews

**Comment by everett-toews** [comment]
We want to keep people reading. You can do what I did at the end of the [interlock tutorial](https://raw.githubusercontent.com/rackerlabs/docs-container-service/master/_tutorials/026-interlock-on-carina.md).
