### ISSUE TITLE
Best practices: Docker Swarm showing up twice in article list

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-container-service#323]
Not sure why but this article is showing up twice in the [article list](https://getcarina.com/docs)

Here are the two links-- they look the same to me, and the article title is also the same.

https://getcarina.com/docs/best-practices/container-ecosystem-docker-swarm/

https://getcarina.com/docs/best-practices/container-ecosystem-docker-swarm/

**Comment by kmsholcomb** [comment]
Same issue as https://github.com/rackerlabs/docs-container-service/issues/443, which Rose assigned to herself.

**Comment by rose-coste** [comment]
Closed by https://github.com/rackerlabs/docs-container-service/pull/461
(sorry I didn't see this earlier report)
