### ISSUE TITLE
That giant TM

### ISSUE THREAD

**Issue by jnoller** [rackerlabs/docs-container-service#355]
for @ktbartholomew 

<img width="582" alt="screen shot 2015-10-25 at 10 31 07 am" src="https://cloud.githubusercontent.com/assets/51528/10716336/a7206428-7b03-11e5-9d6e-ca1906b4b4a1.png">

SO BIG

**Comment by jnoller** [comment]
It's xbox huge

**Comment by ktbartholomew** [comment]
fixed it for ya:
![image](https://cloud.githubusercontent.com/assets/3018940/10716370/a7b2468a-7b04-11e5-8be9-c191fe29cf91.png)

**Comment by jnoller** [comment]
:sob:

**Comment by jnoller** [comment]
fixed in https://github.com/rackerlabs/nexus-control/pull/217
