### ISSUE TITLE
Er, so a funny thing happened on the way to the blog

### ISSUE THREAD

**Issue by jnoller** [rackerlabs/docs-container-service#358]
I am supposing this amazing business opportunity email is not supposed to look like this

https://getcarina.com/blog/announcing-carina/

:squirrel:

**Comment by ktbartholomew** [comment]
Is the issue here the formatting?

**Comment by jnoller** [comment]
Yes I think so. It seems... unstyled.

**Comment by ktbartholomew** [comment]
OK, see https://github.com/rackerlabs/nexus-control/pull/214

Needs @smashwilson to deploy

**Comment by jnoller** [comment]
:cake: :rocket:

**Comment by smashwilson** [comment]
Shipped :+1:
