### ISSUE TITLE
Best-practices: Spacing within and around the tables needs correction

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/docs-container-service#359]
- Need a space between Table 1 and Table 2.
- Need a space between Table 2 and the next paragraph that begins with , "In terms of which ...".
- The spacing between the columns in Table 1 is inconsistent.
- In general, the tables are a little difficult to read. Moving the second column over more would help a lot.      It meshes in with the OrganizationTool column too closely.
- Is OrganizationTool all one word?

https://getcarina.com/docs/best-practices/container-technologies-scheduling-management/

**Comment by ktbartholomew** [comment]
Yikes, tables in general need some TLC. I'll take this.

**Comment by ktbartholomew** [comment]
Fixed with #388.

![image](https://cloud.githubusercontent.com/assets/3018940/10717528/2a6d3322-7b29-11e5-9e9c-ae28263752c1.png)
