### ISSUE TITLE
Best-practices: Unsure about the visual that was copied from another resource

### ISSUE THREAD

**Issue by ReneeRendon** [rackerlabs/docs-container-service#368]
In the Ambassador pattern section, I'm not clear on the visual. Should the dash before the word "networks" be an arrow? 

https://getcarina.com/docs/best-practices/docker-best-practices-container-linking/#resources

**Comment by kmsholcomb** [comment]
Hm. Maybe it should. But because it is a quote., we should leave it as is. Good catch, though!
