### ISSUE TITLE
Stick with segments

### ISSUE THREAD

**Issue by everett-toews** [rackerlabs/docs-container-service#393]
The blog post mentions segments, nodes, and hosts. I'd recommend sticking with segments only. They are the only thing that has an actual definition in the context of Carina (and the [Glossary](https://github.com/rackerlabs/docs-container-service/blob/master/_getting-started/008-glossary.md#segment)).

>Another cool thing is the idea of segments / nodes that you add (Docker hosts in the same cluster).

simply becomes

>Another cool thing is the idea of segments that you add to a cluster.

There are other uses of "hosts" that would have to be replaced too.

**Comment by jnoller** [comment]
Github ate my email back - I'll remove nodes, but I think it's important to point out a segment is a logical docker host (user feedback showed they couldn't grok that)
