### ISSUE TITLE
Getting Started with CLI -- get certificate error 

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-container-service#394]
Article: https://getcarina.com/docs/getting-started/getting-started-carina-cli/

After I install the CLI and configure credentials, run the ```carina list``` command.  Get this error:

```
carina: error: Get https://mycluster.rackspacecloud.com/clusters/maeker123: x509: certificate is valid for app.getcarina.com, not mycluster.rackspacecloud.com, try --help
```

**Comment by jnoller** [comment]
@meker12 Confirm this works with the latest binary; close this bug when confirmed

**Comment by meker12** [comment]
Error result of not having the latest version of the CLI installed.  Based on Jesse's suggestion, changed the download link so that customers can download the latest version from the git repo.

Question now -- how do I know if there's a new version. Will the carina CLI let me know if there's a new version?

**Comment by meker12** [comment]
Downloading the current version of the CLI solved the certificate issue.

**Comment by rgbkrk** [comment]
We can let people know if a new version of the cli is available, I'll add at least that. We can't auto upgrade for folks though.

I'll also get a "latest" link up too. Thanks for reporting this.
