### ISSUE TITLE
Getting Started with CLI - update instructions with Windows commands

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-container-service#405]
Article:  https://getcarina.com/docs/getting-started/getting-started-carina-cli/

```
   Download and install the Carina CLI

Note: Instructions will be updated with Windows-specific commands.
```

**To do:** Add Windows-specific commands.

**Comment by jnoller** [comment]
@carolynvs ^^

**Comment by carolynvs** [comment]
Waiting for https://github.com/getcarina/carina/issues/40 and https://github.com/getcarina/carina/issues/41 to be fixed before I can verify that the Windows commands work.
