### ISSUE TITLE
Remove explicit anchors from section titles

### ISSUE THREAD

**Issue by everett-toews** [rackerlabs/docs-container-service#423]
Some articles have anchors in the section title like this.

    ### <a name="resources"></a>Resources

It's unnecessary as section anchors are automatically generated for us.

**Comment by jnoller** [comment]
:eyes: 

_tutorials/029-docker-networking-basics.md:### <a name="links"></a> Docker links
_tutorials/029-docker-networking-basics.md:### <a name="ambassador"></a> Ambassador pattern
_tutorials/030-connect-docker-containers-with-links.md:### <a name="connect"></a> Connect two containers with a Docker link
_tutorials/030-connect-docker-containers-with-links.md:### <a name="inspect"></a> Inspect the linked containers
_tutorials/034-troubleshooting-port-unavailable.md:### <a name="remove-container"></a> Remove the containers already using the port
_tutorials/034-troubleshooting-port-unavailable.md:### <a name="alternate-port"></a> Publish to an alternative port
_tutorials/034-troubleshooting-port-unavailable.md:### <a name="grow-cluster"></a> Add capacity to the cluster
_tutorials/051-docker-install-linux.md:### <a name="install"></a> Install Docker
_tutorials/051-docker-install-linux.md:### <a name="sudo"></a> Configure Docker to run without sudo
_tutorials/056-load-docker-environment-on-windows.md:### <a name="prerequisites"></a> Prerequisite
_tutorials/056-load-docker-environment-on-windows.md:### <a name="shells"></a> Shells
_tutorials/056-load-docker-environment-on-windows.md:#### <a name="cmd"></a> CMD
_tutorials/056-load-docker-environment-on-windows.md:#### <a name="powershell"></a> PowerShell
_tutorials/056-load-docker-environment-on-windows.md:#### <a name="bash"></a> Bash
_tutorials/056-load-docker-environment-on-windows.md:### <a name="terminals"></a> Terminals
_tutorials/056-load-docker-environment-on-windows.md:#### <a name="cmd-prompt"></a> Windows Command Prompt
_tutorials/056-load-docker-environment-on-windows.md:#### <a name="mintty"></a> Mintty
_tutorials/056-load-docker-environment-on-windows.md:#### <a name="alternatives"></a>Alternatives
_tutorials/056-load-docker-environment-on-windows.md:##### <a name="consolez"></a> ConsoleZ
_tutorials/056-load-docker-environment-on-windows.md:##### <a name="conemu"></a> ConEmu
_tutorials/056-load-docker-environment-on-windows.md:### <a name="references"></a> References
_tutorials/058-carina-credentials.md:### <a name="download"></a> Download credentials
_tutorials/060-troubleshooting-cannot-enable-tty-mode-on-windows.md:### <a name="ssh"></a> Use SSH to connect to the Docker host
_tutorials/060-troubleshooting-cannot-enable-tty-mode-on-windows.md:### <a name="cmd-with-bash"></a> Use the CMD terminal with the Bash shell
_tutorials/060-troubleshooting-cannot-enable-tty-mode-on-windows.md:### <a name="cmd"></a>Use the CMD terminal with the Windows shell
_tutorials/060-troubleshooting-cannot-enable-tty-mode-on-windows.md:### <a name="powershell"></a> Use PowerShell
_tutorials/060-troubleshooting-cannot-enable-tty-mode-on-windows.md:### <a name="other-terminals"></a>Use an alternative terminal
_tutorials/061-preview-jekyll-with-docker-on-linux.md:### <a name="resources"></a>Resources
_tutorials/062-preview-jekyll-with-docker-on-mac.md:### <a name="resources"></a>Resources
_tutorials/063-preview-jekyll-with-docker-on-windows.md:### <a name="resources"></a>Resources

**Comment by carolynvs** [comment]
Sorry about that, didn't realize we got it for free. :smile:

**Comment by rose-coste** [comment]
How will this work for multi-work section headings? Most of what I want to link to now has a 1-word title (Resources) but what if I want to link to something like "Comparisons and recommendations"?

**Comment by carolynvs** [comment]
@rose-coste take the section title, change it to lower-case and replace spaces with hyphens. So a section title of "Comparisons and recommendations" would use `#comparisons-and-recommendations` as the link

**Comment by rose-coste** [comment]
What about titles with special characters, such as "Apache’s Mesos"?
I didn't know about "redcarpet renderer with the with_toc_data plugin" & am not finding user doc for it.  IfI learn more later I can add a section on linking in CONTRIBUTING.md, but for now the "use normal HTML anchors" advice is what's findable when searching for how to cross-reference within a Markdown article, so that's likely to be any new contributor's first try.

**Comment by carolynvs** [comment]
If you would like to know what the anchor is, just preview the page and view the underlying HTML to see what id was assigned. That said, I don't think it's the end of the world if an awkward section title is given a custom defined anchor.

I don't know what we want to recommend in the CONTRIBUTING. Probably the simplified version "Use all lower-case and convert spaces to hyphens. If it is exceptionally long or uses odd characters, feel free to define a custom anchor."

**Comment by kmsholcomb** [comment]
I like that @carolynvs. Anchors are acceptable if needed. I'll add something about creating the links to the Contributing.md file.
