### ISSUE TITLE
Edits for the new info on website

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-container-service#434]
https://github.com/rackerlabs/docs-container-service/blob/master/index.html

@ktbartholomew: I had a few suggested edits, in the attached Word doc, mainly around links and the capitalization of GitHub. Please let me know if you have any questions.

[Join us on GitHub.docx](https://github.com/rackerlabs/docs-container-service/files/20931/Join.us.on.GitHub.docx)

**Comment by jnoller** [comment]
taking this one

**Comment by kmsholcomb** [comment]
Feeding your addiction to track changes...

**Comment by jnoller** [comment]
fixed in https://github.com/rackerlabs/docs-container-service/commit/decf199edc00e0db1ebb20ac933635771c8e425e
