### ISSUE TITLE
Beta label should be on every page of the site

### ISSUE THREAD

**Issue by simonjj** [rackerlabs/docs-container-service#437]
We should make 100% sure that everyone knows that Carina is currently in beta. Let's do so with some sort of header label.

**Comment by kenperkins** [comment]
I agree that it should be more prominent. I threw together an idea where it adds a suffix to the logo, and it looks pretty good. Additionally, doing it this way allows us to call out the beta status when we're in the control panel, which has a different header.

**Comment by ktbartholomew** [comment]
@kenperkins the only problem with modifying the logo is that it only appears on the home page of getcarina.com. We could potentially change the navigation's "Home" link to read "Carina (beta)" and stylized the beta label a little.

**Comment by ktbartholomew** [comment]
accio @technabors

**Comment by kenperkins** [comment]
I think these are actually two separate issues. Beta should be more prominent on the site. Also, the header of getcarina.com should have the logo to reinforce it's not Rackspace proper.

**Comment by kenperkins** [comment]
Opened #438 for the second issue.

**Comment by simonjj** [comment]
@ktbartholomew can we just do an overlay of some sorts, maybe a "hip" version of the corner flag?

**Comment by jnoller** [comment]
Do NOT add to the logo. Legal issues (logo is TM as-is)

**Comment by ktbartholomew** [comment]
oh shoot. I totally forgot that I'm supposed to add a "Carina is in beta" banner to the top that users have to dismiss. I'll do that, which we have designs for already.
