### ISSUE TITLE
Logo should be prominent in header across content site

### ISSUE THREAD

**Issue by kenperkins** [rackerlabs/docs-container-service#438]
Currently, if you're on any page other than the landing page, there's no mention of carina.

For example:

https://getcarina.com/docs/tutorials/create-connect-cluster/

I think we should include the logo in the header so that there's always reinforcement of the branding.

**Comment by kenperkins** [comment]
@ktbartholomew I think you fixed this, yes?

**Comment by ktbartholomew** [comment]
Yep, fixed w/ https://github.com/rackerlabs/nexus-control/pull/225
