### ISSUE TITLE
Create and connect cluster:  Selecting Autoscale gives different output for docker info command

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-container-service#441]
Article: https://getcarina.com/docs/tutorials/create-connect-cluster/
This is a bit of nit -- but when you create a cluster with Autoscale selected, you get more containers, nodes, and images then what is shown in current exampe.  Do we want to mention that? 

docker info command output when Autoscale is selected:

Containers: 8
Images: 6
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 2
 ca5f76f7-aae1-4f69-82a7-2c43a869acf8-n1: 104.130.0.174:42376
  └ Containers: 4
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 2.1 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.18.21-1-rackos, operatingsystem=Debian GNU/Linux 7 (wheezy) (containerized), storagedriver=aufs
 ca5f76f7-aae1-4f69-82a7-2c43a869acf8-n2: 104.130.0.175:42376
  └ Containers: 4
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 2.1 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.18.21-1-rackos, operatingsystem=Debian GNU/Linux 7 (wheezy) (containerized), storagedriver=aufs
CPUs: 24
Total Memory: 4.2 GiB
Name: c4213f7dd01b

**Comment by kmsholcomb** [comment]
I can add a note in the article.

**Comment by kmsholcomb** [comment]
Revised article with https://github.com/rackerlabs/docs-container-service/pull/458
