### ISSUE TITLE
first list item duplicated under All Articles > Best Practices

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-container-service#443]
The list of all articles is divided into 3 groups: Getting Started, Tutorial, Best Practices.
Under Best Practices, the first item is listed twice:

![x2](https://cloud.githubusercontent.com/assets/957576/10734057/60780cde-7bcf-11e5-89c4-b087c5eea5f3.png)

This is happening because the contents of 2 files, 001-container-design-philosophy.md and 002-container-ecosystem-docker-swarm.md, are identical right now; they shouldn't be. 

I'll put the right stuff back into 001-container-design-philosophy.md and check the rest of best-practices for any similar situations.

**Comment by kmsholcomb** [comment]
Same issue as https://github.com/rackerlabs/docs-container-service/issues/323

**Comment by rose-coste** [comment]
closed by https://github.com/rackerlabs/docs-container-service/pull/461
"Best Practices" articles listed first & second are now different from each other
![x1](https://cloud.githubusercontent.com/assets/957576/10740150/8f36ab42-7bee-11e5-8305-85d3b4cf547e.png)

**Comment by meker12** [comment]
Thank you for sorting out the problem Rose.  Looking at the history, it looks like I replaced the content with the Docker Swarm file.  Not sure how I did that, but next time I notice something like this, I'll investigate further rather than leaving it for someone else to sort out.
