### ISSUE TITLE
Asterisks on home page

### ISSUE THREAD

**Issue by DonSchenck** [rackerlabs/docs-container-service#444]
Using Chrome: The following:
Open the login page https://app.getcarina.com/login
Click on the link "Create a free account! to visit https://app.getcarina.com/signup
Use my browser's Back button 

I end up at https://app.getcarina.com/login

but the asterisks from the Sign Up page are still on the page.

![screen shot 2015-10-26 at 12 00 02 pm](https://cloud.githubusercontent.com/assets/5067110/10734334/2668d96a-7bd9-11e5-9c94-006b21dc2ccc.png)

**Comment by ktbartholomew** [comment]
@DonSchenck this looks like a side effect of LastPass. Are you using LastPass?

**Comment by DonSchenck** [comment]
Yes. I'll close this.
