### ISSUE TITLE
Create glossary of container terms

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-container-service#57]
I'll be starting a list of standard terms to use, as well as usage guidelines. Not yet sure where it will live (I suppose somewhere here on GitHub). If you have any suggested "preferred" terms to start the list, add a comment here. For example, during the onsite, Everett mentioned that Docker uses the terms *service*, *daemon*, and *engine* interchangeably. Which term do we use? Also, we talked about how to treat parameters. Do we use the long or short forms? We talked about introducing the long form with the short form on first use, and then using the short form thereafter (like we do with abbreviations and acronyms). These are the kinds of standards we need to establish and use while writing and editing. Post ideas here, and I'll get some lists started.

**Comment by kmsholcomb** [comment]
Created a glossary file PR: https://github.com/rackerlabs/docs-container-service/pull/202

**Comment by lauracly** [comment]
Already merged.
